diskSize: "10Gi"

version: "8.0"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

auth:
  enabled: true
  users:
    - username: "admin"

tls:
  enabled: false
  certSecret: "mosquitto-tls-secret"

service:
  type: "ClusterIP"
  port: 1883
  tlsPort: 8883
