apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Deploying Solr Operator on Kubernetes
name: solr-operator
version: 0.0.1
icon: "https://storage.googleapis.com/zopdev-test-bucket/zop/files/originals/20250403/a45b7860-5846-4fa9-b68d-6765251210bd-solr.png"
dependencies:
  - name: 'zookeeper-operator'
    version: 0.0.1
    repository: https://helm.zop.dev
    condition: zookeeper-operator.install
maintainers:
  - name: ZopDev
    url: zop.dev