{{- range $index, $service := .Values.services }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-{{ $service.database }}-{{ $service.name}}-postgres-configmap
  namespace: {{ $.Release.Namespace }}
data:
  DB_DIALECT: "postgres"
  DB_USER: "{{ $service.name }}_user"
  DB_PORT: "5432"
  DB_NAME: "{{ $service.database }}"
  DB_HOST: "{{ $.Release.Name}}-postgres"
---
{{- end }}