apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-get-password
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-manager-sa
      restartPolicy: Never
      containers:
      - name: kubectl
        image: bitnami/kubectl
        command:
        - /bin/sh
        - -c
        - |
          # Wait for source secret to be available
          echo "Waiting for source secret to be available..."
          until kubectl get secret {{ .Release.Name }}-solrcloud-security-bootstrap -n {{ .Release.Namespace }}; do
            sleep 10
          done
          
          # Get password from source secret
          PASSWORD=$(kubectl get secret {{ .Release.Name }}-solrcloud-security-bootstrap -n {{ .Release.Namespace }} -o jsonpath='{.data.admin}' | base64 --decode)
          
          # Create or patch destination secret
          echo "Creating/updating destination secret with password from source..."
          kubectl create secret generic {{ .Release.Name }}-solrcloud-auth-secret \
            -n {{ .Release.Namespace }} \
            --from-literal=SOLR_PASSWORD="$PASSWORD" \
            --type=Opaque \
            --dry-run=client -o yaml | kubectl apply -f -
          
          echo "Password successfully copied!"