apiVersion: v2
appVersion: "1.0"
description: Helm chart for deploying outline app
name: outline
version: 0.0.3
icon: "https://storage.googleapis.com/zopdev-test-bucket/zop/files/originals/20241129/517f58c3-427a-4cd0-8d37-abe941776827-download1.jpeg"
type: application
dependencies:
  - name: postgres
    version: 0.0.3
    repository:  https://helm.zop.dev
  - name: redis
    version: 0.0.1
    repository: https://helm.zop.dev
  - name: service
    version: 0.0.17
    repository: https://helm.zop.dev
maintainers:
  - name: ZopDev
    url: zop.dev
annotations:
  type: application