apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config
data:
  blackbox.yml: |
    modules:
      https_2xx:
        prober: http
        timeout: 5s
        http:
          method: GET
          preferred_ip_protocol: ip4
          fail_if_not_ssl: true
          valid_status_codes: [200, 301, 302]
          tls_config:
            insecure_skip_verify: false

