apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.prometheus.servicePort }}
      targetPort: {{ .Values.prometheus.servicePort }}
      protocol: TCP
  selector:
    {{- include "prometheus.selectorLabels" . | nindent 4 }}
