apiVersion: v1
appVersion: "1.0"
description: Helm chart for deploying surrealdb
name: surrealdb
version: 0.0.3
icon: "https://storage.googleapis.com/zopdev-test-bucket/zop/files/originals/20241122/c44b7326-00d7-4c62-bce7-ca576509d27f-10982346.png"
maintainers:
  - name: ZopDev
    url: zop.dev
annotations:
  type: datasource