{{- $HTTPS := (and .Values.proxy.https.hosts .Values.proxy.https.enabled) -}}
{{- $autoHTTPS := (and $HTTPS (eq .Values.proxy.https.type "letsencrypt")) -}}
{{- if $autoHTTPS -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jupyterhub.autohttps-serviceaccount.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
{{- end }}
