apiVersion: v2
appVersion: "1.0"
description: Helm chart for deploying cockroachdb datastore
name: cockroachdb
version: 0.0.2
icon: "https://storage.googleapis.com/zopdev-test-bucket/zop/files/originals/20241119/cockroachdb-icon.png"
maintainers:
  - name: ZopDev
    url: zop.dev
annotations:
  type: datasource