apiVersion: v2
appVersion: "1.0"
description: Helm chart for Deploying JupyterHub
name: jupyterhub
version: 0.0.1
type: application
icon: "https://storage.googleapis.com/zopdev-test-bucket/zop/files/originals/20250313/e2540703-3750-4d46-ba32-32445e506332-jupyter.png"
maintainers:
  - name: ZopDev
    url: zop.dev
annotations:
  type: application