{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mosquitto.fullname" . }}-auth
  labels:
    app.kubernetes.io/name: {{ include "mosquitto.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  passwd: |
    {{- range .Values.auth.users }}
    {{ .username }}:{{ .password }}
    {{- end }}
{{- end }}
