{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-auth" (include "mosquitto.fullname" .)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mosquitto.fullname" . }}-auth
  labels:
    app.kubernetes.io/name: {{ include "mosquitto.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  passwd: |
    {{- if $existingSecret }}
    {{ index $existingSecret.data "passwd" | b64dec }}
    {{- else }}
    {{- range .Values.auth.users }}
    {{ .username }}:{{ randAlphaNum 32 }}
    {{- end }}
    {{- end }}
