{{- if .Values.auth.enabled }}
{{- $secretName := printf "%s-auth" (include "mosquitto.fullname" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/name: {{ include "mosquitto.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  passwd: |
    {{- if $existingSecret }}
    {{ index $existingSecret.data "passwd" | b64dec }}
    {{- else }}
    {{- range .Values.auth.users }}
    {{ .username }}:{{ randAlphaNum 32 }}
    {{- end }}
    {{- end }}
{{- end }}
