apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mosquitto.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mosquitto.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mosquitto.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mosquitto
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 1883
            name: mqtt
            {{- if .Values.tls.enabled }}
            - containerPort: 8883
            name: mqtts
            {{- end }}

          volumeMounts:
            - name: config-volume
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /mosquitto/data
            {{- end }}
            {{- if .Values.auth.enabled }}
            - name: auth-secret
              mountPath: /mosquitto/passwords
              readOnly: true
            {{- end }}
            {{- if .Values.tls.enabled }}
            - name: tls-secret
              mountPath: /mosquitto/certs
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "mosquitto.fullname" . }}
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mosquitto.fullname" . }}-pvc
        {{- end }}
        {{- if .Values.auth.enabled }}
        - name: auth-secret
          secret:
            secretName: {{ include "mosquitto.fullname" . }}-auth
        {{- end }}
        {{- if .Values.tls.enabled }}
        - name: tls-secret
          secret:
            secretName: {{ .Values.tls.certSecret }}
        {{- end }}
