apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mosquitto.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  clusterIP: None
  type: {{ .Values.service.type }}
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
    {{- if .Values.tls.enabled }}
    - name: mqtts
      port: 8883
      targetPort: mqtts
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "mosquitto.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
