{{- range $index, $service := .Values.services }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $service.database }}-{{ $service.name}}-mysql-database-secret
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  DB_PASSWORD: {{ $service.password | b64enc }}
---
{{- end }}