{{- range $index, $service := .Values.services }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $service.database }}-{{ $service.name}}-cassandradb-database-secret
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  pod_password: {{  $service.password | b64enc }}
{{- end }}